### ISSUE TITLE
I follow the instructions to install the dependencies, but I get the error:error: command '/usr/local/cuda/bin/nvcc' failed with exit status 1

### ISSUE THREAD

**Issue by amirhamidihd** [Daikenan/LT_DSE#5]
I have installed Cuda 9.0 and I have GTx1080 GPU
this error has been shown when I want to build roi_pool and roi_align in mmdetection folder.

**Comment by Daikenan** [comment]
make sure the version of your gcc and g++ is 5.4.

**Comment by amirhamidihd** [comment]
thanks for your reply, 
your new setup guide helped me and I could test your tracker on my device.
