### ISSUE TITLE
ImportError: cannot import name 'imresize'

### ISSUE THREAD

**Issue by the-nilosch** [Daikenan/LT_DSE#6]
I'm following the instructions, but unfortunately this error occurs, when i try to run LT_DSE_Demo.py

 ```
 File "/mnt/c/git/bsc/LT_DSE/RT_MDNet/rtmdnet_utils.py", line 1, in <module>
    from scipy.misc import imresize
ImportError: cannot import name 'imresize'
```

**Comment by the-nilosch** [comment]
Solved it by downgrading scipy:

`pip3 install scipy==1.1.0 --user`

BUT: A new error occures, maybe it's due tot it?

```
Traceback (most recent call last):
  File "LT_DSE_Demo.py", line 32, in <module>
    from RT_MDNet.tracker import set_optimizer, rt_train
  File "/mnt/c/git/bsc/LT_DSE/RT_MDNet/tracker.py", line 18, in <module>
    from model import *
ModuleNotFoundError: No module named 'model'
```

**Comment by Daikenan** [comment]
The previous script did not specify the version of all packages, which caused problems after some packages were updated. I am sorry for the inconvenience. I have provided a new installation script, and specified the versions of all packages, and successfully tested on two machines.
