### ISSUE TITLE
Error in compile.sh "NotImplementedError: Precise RoI Pooling only supports GPU (cuda) implememtations."

### ISSUE THREAD

**Issue by the-nilosch** [Daikenan/LT_DSE#7]
Prerequisites fulfilled
- CUDA Version 9.2.148
- gcc version 5.4.0
- g++ version 5.4.0
- Ubuntu 16.04.6

**Comment by the-nilosch** [comment]
Further found this messaage while executing compile.sh:
`No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'`

**Comment by the-nilosch** [comment]
If running the code in a Docker Container take care on the image! For me it was:

`docker run -it --name LTDSE -v /home:/home --gpus all nvidia/cuda:9.2-devel-ubuntu16.04 /bin/bash`

**Comment by maryam95hallal** [comment]
I'm working on that project from 4 months and Everything I tried till now failed. I hope that your solution works.
So after the docker installed and running what to do next? I tried to install anaconda to create the environment containing all the dependencies. that didn't workout. please provide the steps I need to do once the docker is running.
thanks in advanced.
